plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.karin.streamtv.player'
    compileSdk 36

    defaultConfig {
        minSdk 23
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = '11'
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation project(':dsp')
    implementation 'androidx.media3:media3-exoplayer:1.9.3'
    implementation 'androidx.media3:media3-common:1.9.3'
    implementation 'androidx.media3:media3-datasource-cronet:1.9.3'
}