org.gradle.jvmargs=-Xmx1536m -Dfile.encoding=UTF-8 -XX:+UseG1GC -XX:MaxGCPauseMillis=200
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
KARIN_STORE_PASSWORD=karintv2026
KARIN_KEY_ALIAS=karintv
KARIN_KEY_PASSWORD=karintv2026
